# when running hexo in a subdirectory (e.g. domain.tld/blog), remove leading slashes ( "/archives" -> "archives" )

version: 3.0
# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: dyanglou,zhumo,朱墨的博客 

# Code Highlight theme
# Available value: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal


menu:
  博客: /
  目录: /categories
  # archives: /archives
  标签: /tags
  关于: /about
  GitHub: https://github.com/dyanglou



# Static files
#vendors: vendors
css: css
js: js
images: images

# Miscellaneous, enter the tracking ID for your Google Analytics
google_analytics: 
